### ISSUE TITLE
Uncertainty in completing an archlab service

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#13]
I'm trying to fill in the service form for an ARCHLAB, and I have some issues to fill in a number of fields and related forms.

- [x] 1.  **Service > Service Techniques**: quite obvious for MOLAB and FIXLAB, but not for ARCHLAB. Should we consider "Archival study" as a technique, or is this a bit of an artificial construct? Since Wednesday, we have set this as a required field with at least one technique, so I have to fill it in. Moreover, it possibly duplicates the "Relevant technique" in the Method schema (see below).

- [x] 2. **Service > Research Disciplines**: controlled list, but none of the values seem very logical for an ARCHLAB service.

- [x] 3. **Service > Service Categories**: missing controlled list, see issue #7 

- [x] 4.  **Service > Service Functions**: missing controlled list, see issue #8 

- [x] 5. **Service > Method Statements**: required field, minimum 1 link to a method. Not clear what a method statement for an ARCHLAB should be, and if ARCHLAB access can be scripted like this. Is every ARCHLAB access not completely different? The current Method form is very much focused on defining methods for analytical techniques (contains techniques, tools, method parameters). Having to fill this in for an ARCHLAB feels a bit artificial.

- [x] 6.  **Service > Resources**: defined as a list of URI's to Collections, Objects, Samples and Archives, and set up as a required field with at least one value. I can set here a link to our knowledge platform, but I can image that not every ARCHLAB has this. Moreover, this overlaps with Service Links.  Either to be removed, or optional.

- [x] 7. **Service > Service Access Period Unit**: defined as an array of controlled list values. I guess this should not be an array, but a single value?

- [x] 8. **Service > Service Access Hours per Unit**: very unclear description, and how does this work if the period unit is set to second or minute?

- [x] 9.  **Method > Alternative labels**: aren't we confusing method names and technique names here? Do we need alternative labels for methods?

- [x] 10. **Method > Method type**: missing controlled list, see issue #11

- [x] 11. **Method > Relevant Technique**: link to a (single) relevant technique, required. See above: does an ARCHLAB method (if an ARCHLAB service should have methods in the first place) have a technique. It also duplicates the techniques defined in the service model. It is my feeling that techniques should only be defined in the method form (not in the service). Not sure if ARCHLAB require techniques to be set, and possible no methods neither

**Comment by jpadfield** [comment]
**1: Service > Service Techniques** - Should we consider a more inclusive top level "term" - when considering your question re-ARCHLAB I have started to list some terms related to "non analytical techniques" and I have the beginnings of a list but it starts to expand to include the concept of consultancy and services relating to helping people setup of improve digital and analogue systems - best practice in relation to Heritage Science. 

From a technical point of view that then leads to the idea of changing the name of "technique" to "service type" or "service class". This would make our lives easier, but then there is the question of everyone else ....

When it comes to defining the Method technique we will have the same issue. We did talk about the fact that the technique concept was duplicated between Service and Method - but people seem to want to tag a service with a technique so we went with both. The other consideration is that when one has multiple Methods offered within one Service the values used might be different a top level term for the service and then more granular terms for the Methods. I expect that for most services the values will be the same.

**Comment by jpadfield** [comment]
**5. Service > Method Statements** - for an ARCHLAB a Method can be quite simple, but I think still important. This document would speak to the level of collaboration, tools, functions and actual access to an archive. Are researchers just shown the door - right up to you are provided with a designated working area and need to request items from the archive to be brought to you. 

Perhaps we just need to do this together and work out how to get it to work and potentially consider the labels and field hints

**Comment by jpadfield** [comment]
**6. Service > Resources** the default value here would need to be a URI/PID for the archive itself. Some archives will already have one but others may need one. If an archive does have web resources and or multiple parts that are individually identified then a series of URIs could be provided.

**Comment by jpadfield** [comment]
**7. Service > Service Access Period Unit** my memory was that this is normally **day** or **hour** for the current services. With the addition of digital services other values **might** be used such as **minute** or **second** or even **millisecond**.

**Comment by jpadfield** [comment]
**8. Service > Service Access Hours per Unit** - This was done to be able to have a consistent period unit in relating to costings I think. We could allow a float number for fractions of an hour if that is required, or we could just get them to agree to change this to **Service Access Milliseconds per Unit**?

**Comment by jpadfield** [comment]
**9. Method > Alternative labels** - I think this was for acronyms? Or potentially codes? But this field could be dropped depending on how it is used

**Comment by jpadfield** [comment]
**11. Method > Relevant Technique** Defining the "technique" at the Method level only could work, but I think the request for it also to be expressed at the service level came from the COO. But as with my comments above, if we altered this to "service type" and allowed for more granular terms to be selected at the Method level, if needed, should make this easier.

**Comment by kobbejager** [comment]
All done
